title: Claudia Website!
email: c@laudiacay.cool
description: >-
  Homepage of Claudia Richoux

baseurl: ""
url: "https://w.laudiacay.cool"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Claudia Richoux"

plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

nav:
  - title: CV
    url: /cv
  - title: About
    url: /about
  - title: Inquiries/Links
    url: /inquiries

pagination:
  enabled: true
  debug: true
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: true
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'tag_page.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tags/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
